
baseURL = "https://example.com/"

[module]
[module.hugoVersion]
min = "0.56.0"
[[module.imports]]
path="github.com/jquery/jquery-dist"
[[module.imports.mounts]]
source="dist/jquery.js"
target="assets/js/slate/lib/_jquery.js"
[[module.imports]]
path="github.com/olivernn/lunr.js"
[[module.imports.mounts]]
source="lunr.js"
target="assets/js/slate/lib/_lunr.js"
[[module.imports]]
path="github.com/slatedocs/slate"
[[module.imports.mounts]]
source="source/images"
target="static/images"
[[module.imports.mounts]]
source="source/fonts"
target="static/fonts"
[[module.imports.mounts]]
source="source/stylesheets"
target="assets/scss/slate"
[[module.imports.mounts]]
source="source/javascripts"
target="assets/js/slate"
